language: en_US

blocked-commands:
  - minimap
  - mm


#You can add your own translations from any mods.
#Unpack .jar mod as zip archive and go to the assets/<mod_name>/lang directory and take any string from json files.
restricted-translations:
  - 'iris.shaders.reloaded'


#How much wait after player join?
#0 is instant check.
#In ticks. 1 seconds = 20 ticks
check-delay: 0


#If check result is TIMEOUT, plugin can retry check
#Works only when player joins server
retries:
  enable: true
  max-retries: 4
  #How much wait after failed try?
  delay: 10

#What api use for packet manipulation?
#ProtocolLib or PacketEvents
#This setting is only applied when both plugins are installed
backend: ProtocolLib

log-resolved-translations: true