name: NMinimapIrisBlocker
version: '1.0.0'
main: su.nezushin.nminimapirisblocker.NMinimapIrisBlocker
api-version: '1.21'
softdepend: [packetevents, NMinimap, ProtocolLib]
commands:
  mib:

libraries:
  - net.kyori:adventure-text-minimessage:4.23.0
  - net.kyori:adventure-platform-bukkit:4.4.0